app:
    resource: "@AppBundle/Controller/"
    type:     annotation
login_homepage:
    path:     /login
    defaults: { _controller: AppBundle:Default:login }

signup_homepage:
    path:     /signup
    defaults: { _controller: AppBundle:Default:signup }
logout:
    path:     /logout
    defaults: { _controller: AppBundle:Default:logout }
