app:
    resource: "@AppBundle/Controller/"
    type:     annotation
login_homepage:
    path:     /login
    defaults: { _controller: AppBundle:Default:login }
signup_homepage:
    path:     /signup
    defaults: { _controller: AppBundle:Default:signup }
logout:
    path:     /logout
    defaults: { _controller: AppBundle:Default:logout }
homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
products:
    path:     /products
    defaults: { _controller: AppBundle:Products:index }
products.add:
    path:     /products/add
    defaults: { _controller: AppBundle:Products:add }
products.delete:
    path:     /products/delete/{id}
    defaults: { _controller: AppBundle:Products:delete }


